#ifndef TSSPS_H
#define TSSPS_H

#include <Common.h>

class TSSPs {
public:
    TSSPs() {};
    void init();
    void update();
    float calculateAngleAddition();
    float ballDir;
    float ballStr;
    float angleAddition;
    bool ballVisible;
private:
    int8_t tsspAdd[TSSP_NUM] = {0};
    uint8_t tsspPins[TSSP_NUM] = {TSSP_PIN_0, TSSP_PIN_1, TSSP_PIN_2, TSSP_PIN_3, TSSP_PIN_4, TSSP_PIN_5, TSSP_PIN_6, TSSP_PIN_7, TSSP_PIN_8, TSSP_PIN_9, TSSP_PIN_10, TSSP_PIN_11, TSSP_PIN_12, TSSP_PIN_13, TSSP_PIN_14, TSSP_PIN_15, TSSP_PIN_16, TSSP_PIN_17, TSSP_PIN_18, TSSP_PIN_19, TSSP_PIN_20, TSSP_PIN_21, TSSP_PIN_22, TSSP_PIN_23};
    float tsspXValues[TSSP_NUM] = {TSSP_X_0, TSSP_X_1, TSSP_X_2, TSSP_X_3, TSSP_X_4, TSSP_X_5, TSSP_X_6, TSSP_X_7, TSSP_X_8, TSSP_X_9, TSSP_X_10, TSSP_X_11, TSSP_X_12, TSSP_X_13, TSSP_X_14, TSSP_X_15, TSSP_X_16, TSSP_X_17, TSSP_X_18, TSSP_X_19, TSSP_X_20, TSSP_X_21, TSSP_X_22, TSSP_X_23};
    float tsspYValues[TSSP_NUM] = {TSSP_Y_0, TSSP_Y_1, TSSP_Y_2, TSSP_Y_3, TSSP_Y_4, TSSP_Y_5, TSSP_Y_6, TSSP_Y_7, TSSP_Y_8, TSSP_Y_9, TSSP_Y_10, TSSP_Y_11, TSSP_Y_12, TSSP_Y_13, TSSP_Y_14, TSSP_Y_15, TSSP_Y_16, TSSP_Y_17, TSSP_Y_18, TSSP_Y_19, TSSP_Y_20, TSSP_Y_21, TSSP_Y_22, TSSP_Y_23};
    int8_t AtsspAdd[TSSP_NUM] = {ROBOT_A_TSSP_ADDITION_0, ROBOT_A_TSSP_ADDITION_1, ROBOT_A_TSSP_ADDITION_2, ROBOT_A_TSSP_ADDITION_3, ROBOT_A_TSSP_ADDITION_4, ROBOT_A_TSSP_ADDITION_5, ROBOT_A_TSSP_ADDITION_6, ROBOT_A_TSSP_ADDITION_7, ROBOT_A_TSSP_ADDITION_8, ROBOT_A_TSSP_ADDITION_9, ROBOT_A_TSSP_ADDITION_10, ROBOT_A_TSSP_ADDITION_11, ROBOT_A_TSSP_ADDITION_12, ROBOT_A_TSSP_ADDITION_13, ROBOT_A_TSSP_ADDITION_14, ROBOT_A_TSSP_ADDITION_15, ROBOT_A_TSSP_ADDITION_16, ROBOT_A_TSSP_ADDITION_17, ROBOT_A_TSSP_ADDITION_18, ROBOT_A_TSSP_ADDITION_19, ROBOT_A_TSSP_ADDITION_20, ROBOT_A_TSSP_ADDITION_21, ROBOT_A_TSSP_ADDITION_22, ROBOT_A_TSSP_ADDITION_23};
    int8_t BtsspAdd[TSSP_NUM] = {ROBOT_B_TSSP_ADDITION_0, ROBOT_B_TSSP_ADDITION_1, ROBOT_B_TSSP_ADDITION_2, ROBOT_B_TSSP_ADDITION_3, ROBOT_B_TSSP_ADDITION_4, ROBOT_B_TSSP_ADDITION_5, ROBOT_B_TSSP_ADDITION_6, ROBOT_B_TSSP_ADDITION_7, ROBOT_B_TSSP_ADDITION_8, ROBOT_B_TSSP_ADDITION_9, ROBOT_B_TSSP_ADDITION_10, ROBOT_B_TSSP_ADDITION_11, ROBOT_B_TSSP_ADDITION_12, ROBOT_B_TSSP_ADDITION_13, ROBOT_B_TSSP_ADDITION_14, ROBOT_B_TSSP_ADDITION_15, ROBOT_B_TSSP_ADDITION_16, ROBOT_B_TSSP_ADDITION_17, ROBOT_B_TSSP_ADDITION_18, ROBOT_B_TSSP_ADDITION_19, ROBOT_B_TSSP_ADDITION_20, ROBOT_B_TSSP_ADDITION_21, ROBOT_B_TSSP_ADDITION_22, ROBOT_B_TSSP_ADDITION_23};
    uint8_t tsspCounter;
    uint8_t tsspValues[TSSP_NUM] = {0};
    uint8_t tsspSortedValues[TSSP_NUM] = {0};
    uint8_t tsspIndexes[TSSP_NUM] = {0};
};

#endif // TSSPS_H